# Generated by Django 6.0.2 on 2026-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='expected_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='delivery',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('PACKS', 'Packs'), ('BOXES', 'Boxes'), ('CANS', 'Cans'), ('BOTTLES', 'Bottles')], default='PCS', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending / Not Sent'), ('SENT', 'Sent to Supplier'), ('RECEIVED', 'Received'), ('PROBLEM', 'Problem / Issue')], default='PENDING', max_length=20),
        ),
    ]
