# Generated by Django 6.0.2 on 2026-02-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_expected_quantity_deliveryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CURRENT', 'Current / Today'), ('SENT', 'Sent (Indicator)'), ('RECEIVED', 'Completed'), ('PROBLEM', 'Problem')], default='PENDING', max_length=20),
        ),
    ]
