# Generated by Django 6.0.2 on 2026-02-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent (Indicator)'), ('RECEIVED', 'Completed'), ('PROBLEM', 'Problem')], default='PENDING', max_length=20),
        ),
    ]
