# Generated by Django 6.0.2 on 2026-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10),
        ),
    ]
