# Generated by Django 6.0.2 on 2026-02-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('current_stock', models.IntegerField()),
                ('type', models.CharField(choices=[('SALE', 'Sale (Deduction)'), ('RESTOCK', 'Restock (Addition)'), ('ADJUST', 'Manual Adjustment')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='inventory.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
