# Generated by Django 6.0.2 on 2026-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price (base price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_to_sell',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price (if different from price)', max_digits=10, null=True),
        ),
    ]
