# Generated by Django 6.0.2 on 2026-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_base_price_product_price_to_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_to_sell',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price (wholesale price)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price (retail price)', max_digits=10),
        ),
    ]
